app:
  name: "EIR SYSTEM"
  port: 8080
  host: "localhost"
  env: "development" # development, production

  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 30s
  max_header_bytes: 1048576 # 1MB

  telegram_bot_token: "your_telegram_bot_token_here"
  telegram_chat_id: "your_telegram_chat_id_here"

  docs_username: "docs_user"
  docs_password: "docs_password"

seed_system_admin:
  full_name: "Example Admin"
  username: "admin"
  password: "admin123"
  phone: "000000000000"

logger:
  level: "info"
  directory: "logs"
  filename: "app.log"
  max_size: 20
  max_backups: 30
  max_age: 30
  compress: true
  console: true
  rotate_daily: true

jwt:
  secret_key: "your_jwt_secret_key_here"
  access_expire_minutes: 15m
  refresh_expire_minutes: 10080m # 7 days

postgres:
  host: "localhost"
  port: 5432
  user: "eir_postgres_user"
  password: "your_postgres_password_here"
  dbname: "eir_system"
  sslmode: "disable"
  timezone: "Asia/Tashkent"

  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: 30m
  conn_max_idle_time: 5m

redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password_here"
  db: 0

  pool_size: 100
  min_idle_conns: 10
  max_retries: 3
  min_retry_backoff: 8ms
  max_retry_backoff: 512ms
  read_timeout: 3s
  write_timeout: 3s
  dial_timeout: 5s

minio:
  host: "localhost"
  root_user: "minio_admin"
  root_password: "your_minio_root_password_here"
  api_port: 9000
  console_port: 9001
  buckets:
    - name: "images"
      public: true
    - name: "videos"
      public: true
    - name: "documents"
      public: false
  use_ssl: false
