services:
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: eir_backend
  #   env_file: .env
  #   ports:
  #     - "${APP_PORT}:8080"
  #   depends_on:
  #     - postgres
  #     - redis

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   container_name: eir_frontend
  #   env_file: .env
  #   ports:
  #     - "${NITRO_PORT}:3000"
  #   depends_on:
  #     - backend

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: eir_postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine3.22
    container_name: eir_redis
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: eir_minio
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:alpine
    container_name: eir_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgresdata:
  redisdata:
  miniodata:
